name: Learn basics of GitHub Actions

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  pre-commit-scans:
        runs-on: ubuntu-latest

        steps:
          - name: Setup java
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '21'
               
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Gitleaks Scan
            uses: actions/checkout@v4
            with:
              args: -paths.

          - name: Checkout Code
            uses: actions/checkout@v1

          - name: OWASP Scan
            uses: zaproxy/action-full-scan@v0.10.0
            continue-on-error: true
            
          - name: Build Code and create docker image
            run: docker build -t api-gateway:latest -f dockerfile .

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{variables.DOCKER_REGISTRY_USER}}
              password: ${{variables.DOCKER_REGISTRY_PASSWORD}}
             # username: ${{secrets.DOCKER_REGISTRY_USER}}
             # password: ${{secrets.DOCKER_REGISTRY_PAT}}

          - name: Tag Docker Image
            run: docker tag api-gateway:latest anujachavan/api-gateway:latest
            
          - name: Push Docker Image
            run: docker push anujachavan/api-gateway:latest

